#!/bin/sh

## restart dwm without logging out
#while true; do
#	# Log stderror to a file 
#	#dwm 2> ~/.dwm.log
#	# No error logging
#	dwm >/dev/null 2>&1
#done

while type dwm >/dev/null ; do dwm && continue || break ; done

